### DISCUSSION TITLE
aio 分支的使用疑问

### DISCUSSION THREAD

**Discussion by JohanChane** [JohanChane/clashtui#38] [Q&A] [answered]
-   我需要手动编写 `clashtui.conf` 文件, 才能使用:

    ```yaml
    current_profile: profile1
    profiles:
      profile1: !Url https://example.com
      config.yaml: File
    ```

-   读配置出错时, 会使用默认配置, 然后退出保存, 我之前的配置会全部清空。
-   建议和 clashtui 的配置路径不相同, 否则两个程序无法同时使用。
-   建议先完善一些基本的使用功能。比如: 导入链接, 模板生成, 选择 profile 等。
-   觉得 Generated 存入生成 yaml 内容和再写一个 yaml 文件, 会有重复, 之后用户如果修改 yaml 文件时, 两者不一, 会有使用歧义。 觉得 clashtui 使用 `clashtui.conf` 不够直观, 但 aio (name?) 分支使用可能比较合理。
