### ISSUE TITLE
[Usage query]: Correct /srv/mihomo when opening clashtui

### ISSUE THREAD

**Issue by hoshF** [JohanChane/clashtui#46]
```
> clashtui
The permissions of the '/srv/mihomo' files are incorrect. clashtui need to run as root to correct. Proceed with running as root? [Y/n]
```

I don't know why I get this question every time I open clashtuiu, and I'm also confused about the difference between mihomo/config.yaml, ~/.config/clashtui/{ basic_clash_config.yaml, templates/*}.

My files under /srv/mihomo/ are like this.

```
uis cache.db config.yaml geoip.metadb
```
The config.yaml file is empty

**Comment by Jackhr-arch** [comment]
I suggest you to install mihomo following [the official setup](https://wiki.metacubex.one/en/startup/service/), or [this one](https://github.com/JohanChane/clashtui/blob/master/README_ZH.md#%E7%94%A8%E6%88%B7%E7%BA%A7%E6%9C%8D%E5%8A%A1%E6%8E%A8%E8%8D%90) (Notice: this is a Chinese page which haven't been translated to English)

The advantage of the later one is that you don't have to be root or `sudo` to run clashtui.

If you still get confused, let us know so we can help and improve the guides.

**Comment by hoshF** [comment]
Unfortunately I still haven't solved this problem, I can only show the current situation as follows

```
 /srv/mihomo  pwd                                                                                ✔ 
/srv/mihomo
 /srv/mihomo  ll                                                                                 ✔ 
总计 13M
drwxr-sr-x 1 mihomo mihomo  430  4月29日 12:07 metacubexd
-rw-r--r-- 1 mihomo mihomo  32K  4月29日 21:14 cache.db
-rw-rw-r-- 1 mihomo mihomo  29K  4月29日 21:29 config.yaml
-rw-r--r-- 1 mihomo mihomo 8.7M  4月29日 11:18 geoip.metadb
-rw-r--r-- 1 mihomo mihomo 4.2M  4月29日 15:59 GeoSite.dat
 /srv/mihomo  groups                                                                             ✔ 
nore mihomo wheel
 /srv/mihomo  clashtui                                                                           ✔ 
The permissions of the '/srv/mihomo' files are incorrect. clashtui need to run as root to correct. Proceed with running as root? [Y/n] ^C
 /srv/mihomo  whoami                                                                  INT ✘  1m 0s 
nore
```

**Comment by Jackhr-arch** [comment]
I'm also not familiar with the '/srv' installation process, but I can show you what I'm currently using.

---

### Clean up

* Backup your profile update urls and templates
* rm your clashtui config dir (`./data` or `~/.config/clashtui`)
* rm your mihomo config dir (`/srv/mihomo`)

### Prepare mihomo configs

* create dir at `~/.local/proxy`
* move mihomo binary to `~/.local/bin`
```
> ls ~/.local/
bin lib  proxy  share  state
> ls ~/.local/bin/
mihomo
> ls ~/.local/proxy/
# empty dir
```
* create a file named `mihomo.service` under `~/.config/systemd/user/`, and copy the following content
``` systemd
[Unit]
Description=mihomo Daemon, Another Clash Kernel.
After=network.target NetworkManager.service systemd-networkd.service iwd.service

[Service]
Type=simple
LimitNPROC=4096
LimitNOFILE=1000000
WorkingDirectory=%h/.local/proxy
Restart=always
ExecStartPre=/usr/bin/sleep 1s
ExecStart=%h/.local/bin/mihomo -d %h/.local/proxy
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=default.target
```
* and then run `systemctl --user daemon-reload`
```
> ls ~/.config/systemd/user/
mihomo.service <some other things>
```

### Download and configure clashtui

* Download from [master branch](https://github.com/JohanChane/clashtui/releases/tag/Continuous_Integration)
* `chmod +x /path/to/clashtui` and then run it, you will be prompted to recreate config dir, type `y`
* modify your clashtui config file at `./data/config.yaml` or `~/.config/clashtui/config.yaml`
``` yaml
basic:
  clash_config_dir: /home/<your user name>/.local/proxy
  clash_bin_path: /home/<your user name>/.local/bin/mihomo
  clash_config_path: /home/<your user name>/.local/proxy/config.yaml
service:
  clash_service_name: mihomo
  is_user: true
timeout: null
edit_cmd: open %s
open_dir_cmd: open %s
```

And now, clashtui should work.

### Enable tun mode

* enter clashtui and switch to `ServiceCTL`, select `SetPermission` and you will be prompted to enter your password.
* or, run `sudo setcap 'cap_net_admin,cap_net_bind_service=+ep' ~/.local/bin/mihomo`

**Comment by Jackhr-arch** [comment]
### How `basic_clash_config.yaml` affect?
Any content in this file will overwrite or append to (rules, rule-provider) selected profile
``` yaml 
# original
external-controller: 127.0.0.1:10000
mixed-port: 3243
log-level: info

# in basic_clash_config.yaml
external-controller: 127.0.0.1:9090
mixed-port: 1242
log-level: error

# mihomo gets
external-controller: 127.0.0.1:9090
mixed-port: 1242
log-level: error
```

### How to make mihomo start on boot?
run `systemctl --user enable mihomo.service`

### What if I login in as someone other than the installer?
mihomo won't start as the service is installed for one user. 

If you need to run mihomo cross users, follow that official setup and modify `config.yaml` to make clashtui work correctly.
Note: if you run mihomo as root, you may need to run clashtui as root, too.
